version: '3'

networks:
    default:

services:
    # multimedia:
    #     image: digitalrepublic/multimedia-worker
    #     build:
    #       context: .
    #       dockerfile: docker/multimedia-worker/Dockerfile
    #     environment:
    #         CLOUDIVE_S3_ENDPOINT: "minio:9000"
    #         CLOUDIVE_S3_ACCESS_KEY_ID: "WN1GBWAZZ9FFBKJBKKOG"
    #         CLOUDIVE_S3_SECRET_ACCESS_KEY: "0vHZesPBciElr7+vnRB2DTzpXzp9uVkmjhaTbeat"
    #         CLOUDIVE_S3_SSL_ENABLED: "false"
    # filter:
    #     image: digitalrepublic/cloudive-mailer
    #     build:
    #       context: .
    #       dockerfile: docker/master/Dockerfile
    #     environment:
    #         CLOUDIVE_KAFKA_INBOUND_QUEUE: "s3notifications"
    #         CLOUDIVE_KAFKA_OUTBOUND_QUEUE: "thumb-worker-queue"
    #         CLOUDIVE_S3_ENDPOINT: "minio:9000"
    #         CLOUDIVE_S3_ACCESS_KEY_ID: "WN1GBWAZZ9FFBKJBKKOG"
    #         CLOUDIVE_S3_SECRET_ACCESS_KEY: "0vHZesPBciElr7+vnRB2DTzpXzp9uVkmjhaTbeat"
    #         CLOUDIVE_S3_SSL_ENABLED: "false"
    # minio:
    #     build:
    #       context: .
    #       dockerfile: docker/minio/Dockerfile.dev
    #     command: "minio server /exports"
    #     ports:
    #         - "9000:9000"
    #     depends_on:
    #         - "kafka"
    #     environment:
    #         KAFKA_BROKERS: "kafka:9092"
    #         MINIO_ACCESS_KEY: "WN1GBWAZZ9FFBKJBKKOG"
    #         MINIO_SECRET_KEY: "0vHZesPBciElr7+vnRB2DTzpXzp9uVkmjhaTbeat"
    #         MINIO_REGION: "us-east-1"
    #     restart: on-failure

    kafka:
        image: ches/kafka
        depends_on:
          - zookeeper
        environment:
          ZOOKEEPER_IP: zookeeper
        ports:
          - "9092:9092"

    zookeeper:
        image: zookeeper:3.4
        restart: unless-stopped
        ports:
          - 2181
