[meta]
  log-level = "debug"

[httpd]
  enabled = true
  bind-address = "0.0.0.0:9009"

[kafka]
  brokers = ["kafka:9092"]
  inbound-queue = "s3notifications"
  outbound-queue = "thumb-worker-queue"
[transform]
  [transform.formats.thumbnail]
    width = 100
    height = 100
    quality = 90
    name = "thumbnail"
  [transform.formats.squarethumb]
    width = 75
    height = 75
    quality = 90
    name = "squarethumb"
  [transform.formats.small]
    width = 240
    height = 240
    quality = 90
    name = "small"
  [transform.formats.large]
    width = 800
    height = 600
    quality = 90
    name = "medium"
[s3]
  ssl-enabled = false
  endpoint = "minio:9000"
  access-key-id = "WN1GBWAZZ9FFBKJBKKOG"
  secret-access-key = "0vHZesPBciElr7+vnRB2DTzpXzp9uVkmjhaTbeat"