apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "thumb-service.fullname" . }}-master
  labels:
    app: {{ template "thumb-service.name" . }}
    chart: {{ template "thumb-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "thumb-service.name" . }}
      release: {{ .Release.Name }}
      role: master
  template:
    metadata:
      labels:
        app: {{ template "thumb-service.name" . }}
        release: {{ .Release.Name }}
        role: master
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: {{ .Chart.Name }}-master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          env:
          - name: ROOVE_KAFKA_BROKERS
            value: {{.Values.kafka.brokers}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
